/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cube_example_com_cube_JniUtils */

#ifndef _Included_cube_example_com_cube_JniUtils
#define _Included_cube_example_com_cube_JniUtils

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cube_example_com_cube_JniUtils
 * Method:    findSquares
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cube_example_com_cube_JniUtils_findSquares
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
